### ISSUE TITLE
Script does not convert all rows

### ISSUE THREAD

**Issue by xrowdominik** [ezsystems/ezplatform-xmltext-fieldtype#60] opened 2018-07-24 13:20 UTC
Hey there,

we are running this command on a huge database with around 4 million rows to convert. The script sometimes suddenly stops and says for example: 

> Converted 39840 ezxmltext fields to richtext

If I check the database afterwards there are still rows that need convertion. After restarting the command I´m getting the output that even the command found the rows to convert:

> Found 19429 field rows to convert.

Do you have any idea what causes this problem? We need a fix asap because we are not able to check every hour if the script is still running or not.

**Comment by andrerom** [comment] 2018-07-24 14:40
If you expect support here, then please use support.

As for knowing what it stops on, there are several new arguments you can use now to debug the conversion. Unfortunately it is _your_ database, so you are better placed at answering your question.

**Comment by vidarl** [comment] 2018-08-09 07:25
FYI : If it is memory_limit related, this might help you : https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/65

**Comment by amauryvallier** [comment] 2018-08-22 08:26
I have had the same problem. After several tests, it seems indeed to be memory related.

The main problem is that the script tells you that all your lines have been converted even if it is not the case and ends prematurely because of the memory limit. Maybe it should be precised on the documentation to use the `php -d memory_limit=-1 bin/console`or to launch the command several times to make sure you have all your lines converted, as it can be confusing.

While I'm here, I've been using this script for some time now and it keeps on getting better and working with even more exotic cases. This is great, thank you all!

**Comment by vidarl** [comment] 2018-08-22 13:30
when I tested memory limit stuff with this script, php has returned a non-zero exit status so the script has detected the problem.  You should see the "PHP Fatal Error: Allowed memory size (...)" message and the script should abort.

Based on your feedback, it seems like php is not always capable of doing that. Are you able to reproduce it reliably?

**Comment by vidarl** [comment] 2018-08-22 13:36
Also, if I try to kill a child using SIGKILL (which is what the OOM killer in linux would do), I get a non-zero exit status and the script aborts with

**Comment by vidarl** [comment] 2018-11-27 15:17
I am able to reproduce the reported problem. Working on a fix

**Comment by vidarl** [comment] 2018-11-29 09:38
FYI : https://jira.ez.no/browse/EZP-29846

**Comment by vidarl** [comment] 2019-11-14 10:28
Fixed in https://github.com/ezsystems/ezplatform-xmltext-fieldtype/commit/ee587fea1eb5714a47d0e6a49c59f8d8b6140eba

**Closed by vidarl** 2019-11-14 10:28 UTC
