### ISSUE TITLE
EZP-29116 : Conversions from ezxmltext to ezrichtext fails if ezmltext have duplicate xhtml ids

### ISSUE THREAD

**Issue by cadum34** [ezsystems/ezplatform-xmltext-fieldtype#27] opened 2017-12-04 10:11 UTC
Hello, i'm on ez 5.9 and I want to migrate on ezplatform. When i run convert script I have an error: 
[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: DOMDocument::loadXML(): ID inv5 already defined in Entity, line: 2 

My xmlString is: 
```
<?xml version="1.0" encoding="utf-8"?>
<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/">
<paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/">
<ul>
 <li>
  <paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/">
    <line><link target="_blank" xhtml:id="inv5" url_id="2309">Cottage Pécharmant 6 pers 3 ch 2sdb FO4</link></line>
    <line> </line>
  </paragraph>
 </li>
 <li>
```

How can i resolve the problem? 
Thanks

**Comment by elabayoub** [comment] 2017-12-18 16:59
Take a look at the issue #29, it may help.

**Comment by andrerom** [comment] 2017-12-19 08:55
_Note: please keep issue open even if manually removing them works, should at some point add a pass fixing this for migration._

**Comment by vidarl** [comment] 2018-04-11 12:10
This error is caused by the fact that  your content object contains multiple elements which has the id="inv5"
The id's must be unique, ref ref. https://www.w3schools.com/html/html_id.asp.

I don't think this is an id generated by ezpublish, but by your editor. Ids can be added to links using for instance the editor. And it doesn't look like ezpublish complains if you provide a non-unique id...

I did a quick look in the editor(5.4), and it seems like link elements are the only ones which the user may assign ids to.
Looking at the [XSLT]( https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/ezxml/docbook/core.xsl) it seems that ids are supported on embed and embed-inline too though

@andrerom : What is the resolution here? 
The bug is caused by invalid user input. 
Should I add a pass fixing this ( loop over all links/embed/embed-inline) in the document and check if the ids (if given) are unique. I don't think this is doable in XSLT and would need to be done in PHP.

**Comment by andrerom** [comment] 2018-04-12 07:15
There are two options here;
A: We map this to a custom id which does not need to be unique
B: We change the converter to omit duplicates, keeping only the first one and writing warning about it _(Please check this: I'm assuming browsers will  scroll to first one if there are several on anchor links)_

**Comment by vidarl** [comment] 2018-04-18 10:50
I'll try to fix this in XSLT, and will therefore fore go option A. If our xslt processor can deal with  `<xsl:message>` it would be possible to warn the user. If not, the transformation will be done silently

**Comment by vidarl** [comment] 2018-04-18 12:29
Our xslt processor (libxml) didn't deal with `<xsl:message>` that well. `<xsl:message terminate="no">`and `<xsl:message terminate="yes">` is treated the same ( as errors ), and I see no way of detecting that we are dealing with a non-fatal error ( Expect for formatting the error message itself in a particular way to indicate it is a non-fatal one.... ) 

Also, Adding a custom id (like `data-duplicated-id` ) will cause a validation error, so I don't think it is possible to simply add that without adding support for it in ezrichtext.

What about including the duplicated id in the new id and add a random unique identifier afterwards:
id="inv5" ==> id="duplicated_id_inv5_idm46042491882000"

We can the scan the resulting xml in PHP and search for duplicated_id and output a warning

**Comment by andrerom** [comment] 2018-04-18 12:41
> id="inv5" ==> id="duplicated_id_inv5_idm46042491882000"

just for the duplicates? so not if it's onely one of it? if so: yes that is fine with me

**Comment by vidarl** [comment] 2018-04-18 12:42
yes, only for the duplicates. Unique ids will remain as-is

**Comment by vidarl** [comment] 2018-04-19 11:51
Create jira issue : https://jira.ez.no/browse/EZP-29116

**Comment by vidarl** [comment] 2018-05-31 11:49
Fixes has been merged, so closing issue

**Closed by vidarl** 2018-05-31 11:49 UTC
Labels: Migration
