### ISSUE TITLE
    EZP-29135  Converting ezxmltext to richtext when embed tag contains neither node_id or object_id fails

### ISSUE THREAD

**Issue by supasteev0** [ezsystems/ezplatform-xmltext-fieldtype#26] opened 2017-11-22 08:02 UTC
Hello, 

I just tried to run the migration script on one of our projects and got the following error : 

`Found 0 field definiton to convert.
Converted 0 ezxmltext field definitions to ezrichtext
Found 68476 field rows to convert.

                                                                                                          
  [eZ\Publish\Core\Base\Exceptions\InvalidArgumentException]                                              
  Argument '$xmlDoc' is invalid: Transformation of XML content failed: Error in 0:0: Unhandled link type  
                                                                                                          

Exception trace:
 () at /var/www/asn-ezplatform/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/FieldType/RichText/Converter/Xslt.php:141
 eZ\Publish\Core\FieldType\RichText\Converter\Xslt->convert() at /var/www/asn-ezplatform/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/FieldType/RichText/Converter/Aggregate.php:44
 eZ\Publish\Core\FieldType\RichText\Converter\Aggregate->convert() at /var/www/asn-ezplatform/vendor/ezsystems/ezplatform-xmltext-fieldtype/bundle/Command/ConvertXmlTextToRichTextCommand.php:255
 EzSystems\EzPlatformXmlTextFieldTypeBundle\Command\ConvertXmlTextToRichTextCommand->convert() at /var/www/asn-ezplatform/vendor/ezsystems/ezplatform-xmltext-fieldtype/bundle/Command/ConvertXmlTextToRichTextCommand.php:188
 EzSystems\EzPlatformXmlTextFieldTypeBundle\Command\ConvertXmlTextToRichTextCommand->convertFields() at /var/www/asn-ezplatform/vendor/ezsystems/ezplatform-xmltext-fieldtype/bundle/Command/ConvertXmlTextToRichTextCommand.php:93
 EzSystems\EzPlatformXmlTextFieldTypeBundle\Command\ConvertXmlTextToRichTextCommand->execute() at /var/www/asn-ezplatform/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at /var/www/asn-ezplatform/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:863
 Symfony\Component\Console\Application->doRunCommand() at /var/www/asn-ezplatform/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:196
 Symfony\Component\Console\Application->doRun() at /var/www/asn-ezplatform/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/asn-ezplatform/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/asn-ezplatform/app/console:29`

Any idea where this could come from ?

**Comment by andrerom** [comment] 2017-11-22 08:57
This one might be new to me _(I know about one where`§:DomDocument:§` gets added at start of xml document during conversion and hence failing at later stage)_.

Also Seems like we have some work to do on the error handling to make them output more information at least.  
@pspanja Have you happened to have seen issues like this in the past?

**Comment by pspanja** [comment] 2017-11-22 09:11
@andrerom I didn't see that before, but found something here that might be related: https://jira.ez.no/browse/EZP-26384

**Comment by andrerom** [comment] 2017-11-22 09:14
@supasteev0 I guess you are on a newer version of Platform then that, but can you past `composer show | grep ezsystems/` ?

**Comment by pspanja** [comment] 2017-11-22 09:23
Seems like the fix there was on the client side, the error is probably coming from here:
https://github.com/ezsystems/ezpublish-kernel/blob/7170576929fefd6c1bb240f13553b14ca721ca43/eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/ezxml/docbook/core.xsl#L509

So something about embed link that is not handled, would be good to see `ezxml` source that is causing this.

**Comment by supasteev0** [comment] 2017-11-22 11:03
@andrerom Here is the output from composer info | grep ezsystems/

`composer info | grep ezsystems/
ezsystems/behatbundle                        v6.5.1             Behat bundle for help testing eZ Bundles and projects
ezsystems/content-on-the-fly-prototype       v0.1.11            Platform UI Content on the Fly feature
ezsystems/date-based-publisher               v1.4.0             Date-based Publisher bundle
ezsystems/ez-support-tools                   v0.1.3             Providing information about the system eZ Platform/Studio is running on
ezsystems/ezautosave-ls                      v5.4.2             Content editing autosave extension for eZ Publish legacy
ezsystems/ezdemo-ls-extension                v5.4.2             eZ Publish Legacy Demo Website extension
ezsystems/ezfind-ls                          v5.4.9             eZ Find is a search extension for eZ Publish legacy, providing more functionality and better results than the default search in eZ Publish.
ezsystems/ezflow-ls-extension                v5.3.12            eZ Publish Legacy Flow extension
ezsystems/ezgmaplocation-ls-extension        v5.3.1             eZ Publish Legacy map location datatype extension
ezsystems/ezie-ls                            v5.3.1             An image editor for simple and usual image modifications integrated in the editing interface of any eZ Publish Content Object that has at le...
ezsystems/ezmbpaex-ls                        v5.3.2             eZ Publish Legacy Extension that provides functionality for password expiration and validation.
ezsystems/ezmultiupload-ls                   v5.3.1.2           Multi-upload extension for eZ Publish legacy
ezsystems/ezodf-ls                           v5.3.8             This extension enables import and export of OpenOffice.org Writer documents within eZ Publish legacy
ezsystems/ezplatform-design-engine           v1.1.0             Design fallback mechanism for eZ Platform
ezsystems/ezplatform-ee-assets               v2.0.0             External assets dependencies for StudioUIBundle
ezsystems/ezplatform-http-cache              v0.2.4             HTTP cache handling for eZ Platform.
ezsystems/ezplatform-i18n                    v1.4.0             Meta repository to store every eZ Platform translations. This should be used during development to ease synchronization with Crowdin. SHOULD...
ezsystems/ezplatform-multi-file-upload       v0.1.3             Multi File Upload for eZ Platform
ezsystems/ezplatform-solr-search-engine      v1.5.0             Solr search engine implementation for eZ Platform
ezsystems/ezplatform-xmltext-fieldtype       v1.4.0             XmlText field type implementation for eZ Platform
ezsystems/ezprestapiprovider-ls              v5.3.0             eZ Publish REST API v1 content provider
ezsystems/ezpublish-kernel                   v6.12.0.2          Kernel used by ezsystems/ezplatform and derivatives. Provides the Content Repository, its APIs, and the application's Symfony framework inte...
ezsystems/ezpublish-legacy                   v2017.10.1         eZ Publish LegacyStack (4.x)
ezsystems/ezpublish-legacy-installer         v2.0.4             Installer for eZ Publish legacy extensions and legacy kernel itself.
ezsystems/ezstarrating-ls-extension          v5.3.2             eZ Publish Legacy starrating extension
ezsystems/ezstudio-cron                      v1.0.0             Cron bundle
ezsystems/ezstudio-form-builder              v1.3.0.1           Form Builder for eZ Studio
ezsystems/ezstudio-installer                 v1.5.0             Installer for eZ Studio
ezsystems/ezstudio-notifications             v1.2.0             Notification extension for eZ Studio
ezsystems/ezwt-ls-extension                  v5.3.8             eZ Publish Legacy website toolbar extension
ezsystems/flex-workflow                      v1.9.0             Flex Workflow extension for eZ Studio
ezsystems/landing-page-fieldtype-bundle      v1.12.0            eZ Platform Landing Page FieldType
ezsystems/legacy-bridge                      v1.4.0.1           eZ Platform bridge to eZ Publish Legacy
ezsystems/platform-ui-assets-bundle          v4.0.0             External assets dependencies for PlatformUIBundle
ezsystems/platform-ui-bundle                 v1.12.0.1          eZ Platform UI Bundle
ezsystems/repository-forms                   v1.10.0            Use Symfony forms with eZ Platform repository objects
ezsystems/studio-ui-bundle                   1.12.0             eZ Studio UI Bundle
`

**Comment by andrerom** [comment] 2017-11-22 12:52
@supasteev0 do you also happen to have some xmlText _(raw xml from db before the attempt to convert)_ affected by this?

**Comment by supasteev0** [comment] 2017-11-22 13:13
@andrerom You mean you would like to know which raw xml text is causing this error ?
If so, how can I find which xmltext attribute is causing this error ? as the error output is not very verbose about which attribute is being converted ...
I actually just tried to run the migration script to see if the project could be fully migrated to ezplatform-ee,  but I'm still in the migration process at the moment.

**Comment by andrerom** [comment] 2017-11-23 11:52
> You mean you would like to know which raw xml text is causing this error ?

yes

> If so, how can I find which xmltext attribute is causing this error ? as the error output is not very verbose about which attribute is being converted ...

I know, you would have to add some brute force debug in there to dump the xml.
Using that we can in next step enhance it to make it give more relevant info (once we know what is relevant).

**Comment by supasteev0** [comment] 2017-11-23 13:25
@andrerom Here is the raw content of the xmltext attribute that fails to be converted : 

``` xml
<?xml` version="1.0" encoding="utf-8"?>
<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><embed class="right" view="embed" size="original" align="right"/></paragraph><section><section><section><header>Téléchargement du guide :</header><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59918">Guide complet</link> (987 ko)</paragraph></li><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59919">Guide sans les annexes</link> (289 ko)</paragraph></li></ul></paragraph></section></section></section><section><section><section><header>Téléchargement des annexes du guide :</header><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><line>Les formulaires de déclaration :</line><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59920">Formulaire de déclaration applicable à une INB</link> (147 ko)</paragraph></li><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59921">Formulaire de déclaration applicable au transport de matières radioactives</link> (118 ko)</paragraph></li></ul></paragraph></section></section></section><section><section><section><header>Les modèles de compte-rendus d'événement significatif :</header><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59922">Compte rendu d'événement significatif applicable à une INB</link> (128 ko)</paragraph></li><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59923">Compte rendu d'événement significatif de transport de matières radioactives</link> (277 ko)</paragraph></li><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59924">Repères méthodologiques pour l'utilisation du modèle de compte rendu d'événement significatif</link> (122 ko)</paragraph></li></ul></paragraph></section></section></section><section><section><section><header>Les critères de déclaration :</header><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><line>Les critères définis par l'ASN permettent d'identifier parmi tous les événements détectés ceux qu'elle considère comme significatifs. L'ASN distingue des critères relatifs :</line><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><line>à la sûreté: </line><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59925">des réacteurs à eau pressurisée</link> (190 ko)</paragraph></li><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59926">des INB autres que les réacteurs à eau pressurisée</link> (134 ko)</paragraph></li><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59927">du transport de matières radioactives</link> (108 ko)</paragraph></li></ul><line> </line></paragraph></li></ul><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59928">à la radioprotection des travailleurs et du public</link> (147 ko) ;</paragraph></li></ul><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59929">à la protection de l'environnement</link> (134 ko).</paragraph></li></ul></paragraph></section></section></section><section><section><section><header>Le glossaire :</header><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><link node_id="59930">Télécharger le glossaire</link> (77 ko)</paragraph></li></ul></paragraph></section></section></section></section>
```

**Comment by cadum34** [comment] 2017-12-01 08:46
Hello, i'm on ez 5.9 and I want to migrate on ezplatform. When i run convert script I have an error: 
[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: DOMDocument::loadXML(): ID inv5 already defined in Entity, line: 2 

My xmlString is: 
string(2060) "<?xml version="1.0" encoding="utf-8"?>
<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><ul><li><paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/"><line><link target="_blank" xhtml:id="inv5" url_id="2309">Cottage Pécharmant 6 pers 3 ch 2sdb FO4</link></line><line> </line></paragraph></li><li>"...

How can i resolve the problem? 
Thanks

**Comment by andrerom** [comment] 2017-12-04 10:16
If any of you are having this issue on a eZ Platform Enterprise install, please report this to eZ Support so they can have a look. Otherwise best bet is to either try to propose fixes or see if anyone in the community is able to help.

**Comment by vidarl** [comment] 2018-04-30 12:43
The cause of the problem is this embed tag:

        <embed class="right" view="embed" size="original" align="right"/>

which contains neither object_id or node_id.. So it is invalid..

I have two proposals for a solution:
1. Silently remove the embed tag in xslt
2. in xslt, rewrite it to `xlink:href=ezlocation://0` ( which should not exists ) and then in PHP output warning

**Comment by vidarl** [comment] 2018-06-28 09:38
Closing this as fix for EZP-29135 has been merged (pending QA though)

**Closed by vidarl** 2018-06-28 09:38 UTC
Labels: Migration
